openapi: 3.0.3
info:
  title: Pub/Sub Gateway
  description: HTTPを通してPub/Subが使えるようにするゲートウェイサーバ
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /v1/gcp/publish/{topic}:
    post:
      tags:
      - gcp
      summary: publish gcp
      description: httpプロトコルを経由してCloud Pub/Subにメッセージを渡すエンドポイント
      operationId: gcp#publish
      parameters:
      - name: topic
        in: path
        description: Cloud Pub/SubのTopic
        required: true
        schema:
          type: string
          description: Cloud Pub/SubのTopic
          example: "53"
          minLength: 1
        example: z5
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishRequestBody'
            example:
              message: "166"
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PubsubGatewayGcpPublish'
              example:
                id: Sed fugiat ipsam vero eligendi iusto.
  /v1/healthz/liveness:
    get:
      tags:
      - healthz
      summary: liveness healthz
      description: サーバが生きているかチェックするエンドポイント
      operationId: healthz#liveness
      responses:
        "200":
          description: OK response.
        "500":
          description: Internal Server Error response.
  /v1/healthz/readiness:
    get:
      tags:
      - healthz
      summary: readiness healthz
      description: サーバが準備完了状態でいるかチェックするエンドポイント
      operationId: healthz#readiness
      responses:
        "200":
          description: OK response.
        "500":
          description: Internal Server Error response.
components:
  schemas:
    PublishRequestBody:
      type: object
      properties:
        message:
          type: string
          description: Cloud Pub/SubのメッセージBody
          example: "y"
          minLength: 1
      example:
        message: w41
      required:
      - message
    PubsubGatewayGcpPublish:
      type: object
      properties:
        id:
          type: string
          description: message id
          example: Assumenda inventore cumque.
      example:
        id: Consequatur velit dicta.
      required:
      - id
tags:
- name: gcp
  description: Google Cloud Pub/Sub向けサービス
- name: healthz
  description: ヘルスチェックサービス
