settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
- name: testing-subscriber-v1
  path: /go/src/github.com/PyYoshi/pubsub-gateway/cmd/testing_subscriber
  commands:
    vet:
      status: false
    fmt:
      status: false
    generate:
      status: false
    install:
      status: false
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - ../../
    ignored_paths:
      - ../../.dep
      - ../../.git
      - ../../.realize
      - ../../vendor
